export const reportsCardData = [
  {
    id: '1',
    title: 'Total Overtime',
    time: '8h 30m',
    description: 'Extra time spent',
    iconName: 'access-time',
  },
  {
    id: '2',
    title: 'Total Short Time',
    time: '2h 15m',
    description: 'Less time spent',
    iconName: 'timer-off',
  },
  {
    id: '3',
    title: 'Total Classes',
    time: '15 Classes',
    description: 'Classes attended',
    iconName: 'class',
  },
  {
    id: '4',
    title: 'Total Time Spent',
    time: '40h 00m',
    description: 'Overall time spent',
    iconName: 'schedule',
  },
];

export const dummyData = [
  {
    className: 'Class 10A',
    classTime: '9AM to 10AM',
    punchInTime: '9:05 AM',
    punchOutTime: '9:50 AM',
    arrivalStatus: 'Arrival 5 Minutes Late',
    exitStatus: 'Left 10 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
  {
    className: 'Class 10B',
    classTime: '10AM to 11AM',
    punchInTime: '10:00 AM',
    punchOutTime: '10:55 AM',
    arrivalStatus: 'On Time',
    exitStatus: 'Left 5 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
  {
    className: 'Class 10A',
    classTime: '9AM to 10AM',
    punchInTime: '9:05 AM',
    punchOutTime: '9:50 AM',
    arrivalStatus: 'Arrival 5 Minutes Late',
    exitStatus: 'Left 10 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
  {
    className: 'Class 10B',
    classTime: '10AM to 11AM',
    punchInTime: '10:00 AM',
    punchOutTime: '10:55 AM',
    arrivalStatus: 'On Time',
    exitStatus: 'Left 5 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
  {
    className: 'Class 11A',
    classTime: '9AM to 10AM',
    punchInTime: '9:05 AM',
    punchOutTime: '9:50 AM',
    arrivalStatus: 'Arrival 5 Minutes Late',
    exitStatus: 'Left 10 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
  {
    className: 'Class 11B',
    classTime: '10AM to 11AM',
    punchInTime: '10:00 AM',
    punchOutTime: '10:55 AM',
    arrivalStatus: 'On Time',
    exitStatus: 'Left 5 Minutes Early',
    punchInPhoto: 'https://via.placeholder.com/150',
    punchOutPhoto: 'https://via.placeholder.com/150',
  },
];
